---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KipKips.
--- DateTime: 2020.3.18 21:30
---
mytable = {"apple", "orange", "banana"}
--以K字节数为单位返回Lua使用的总内存数,这个值有小数部分,乘上1024就能得到Lua使用的准确字节数(除非溢出)
print(collectgarbage("count")*1024)
mytable = nil
print(collectgarbage("count")*1024)
print(collectgarbage("collect"))
print(collectgarbage("count")*1024)