---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/27 9:35
---测试正则表达式匹配中文
---
tab={"王琨鹏","刷卡等级","纳斯达克发","法第四回复大师傅是发","王琨鹏"}
print("干嘛啊你")
print("adsada")
print("ad为己任挖喝奶粉da")
