---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KipKips.
--- DateTime: 2020/3/16 19:45
---
Module={}
Module.var="wkp"
--函数的第一种声明方式
Module.fun1= function()
    print("这是Module模块的fun1函数")
end
--函数的第二种声明方式
function Module.fun2()
    print("这是Module模块的fun2函数")
end

return Module