---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KipKips.
--- DateTime: 2020.3.16 21:58
---

m=require("Module")
print(Module.var)
Module.fun1()
Module.fun2()
Module.fun3()

--使用接收变量调用
m.fun1()